name: Reusable Deploy
on: 
    workflow_call:
        inputs:
            artifact-name:
                description: The name of the artifact to deploy
                required: false
                default: dist
                type: string
        outputs:
            result:
                description: The result of the deployment
                value: ${{ jobs.deploy.outputs.outcome }}

jobs:
  deploy:
    outputs:
        outcome: ${{ steps.set-result.outputs.res }}
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
      - name: Output contents
        run: ls -la 
      - name: Output information
        run: echo "Deploying & uploading..."

      - name: set result output
        id: set-result
        run: echo "res=Deployment successful" >> $GITHUB_OUTPUT